create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  display_name text not null default '新朋友',
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.items (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 120),
  category text not null check (category in ('food', 'drink', 'gear', 'other')),
  quantity text not null,
  note text,
  claimed_by uuid references public.profiles(id) on delete set null,
  created_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now()
);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references public.profiles(id) on delete cascade,
  action text not null,
  detail text not null,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, email, display_name) values (new.id, new.email, coalesce(new.raw_user_meta_data->>'display_name', '新朋友'));
  return new;
end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.claim_item(item_id bigint) returns public.items language plpgsql security definer set search_path = public as $$
declare result public.items;
begin
  update public.items set claimed_by = auth.uid() where id = item_id and claimed_by is null returning * into result;
  if result.id is null then raise exception '這項物品已被其他人認領或不存在'; end if;
  return result;
end; $$;
create or replace function public.unclaim_item(item_id bigint) returns public.items language plpgsql security definer set search_path = public as $$
declare result public.items;
begin
  update public.items set claimed_by = null where id = item_id and claimed_by = auth.uid() returning * into result;
  if result.id is null then raise exception '只能取消自己認領的物品'; end if;
  return result;
end; $$;

alter table public.profiles enable row level security;
alter table public.items enable row level security;
alter table public.activity_logs enable row level security;
create policy "profiles are readable by signed in users" on public.profiles for select to authenticated using (true);
create policy "items are readable by signed in users" on public.items for select to authenticated using (true);
create policy "signed in users can add items" on public.items for insert to authenticated with check (created_by = auth.uid());
create policy "admins can delete items" on public.items for delete to authenticated using ((select is_admin from public.profiles where id = auth.uid()));
create policy "users can read logs" on public.activity_logs for select to authenticated using ((select is_admin from public.profiles where id = auth.uid()));
create policy "signed in users can add logs" on public.activity_logs for insert to authenticated with check (actor_id = auth.uid());
grant execute on function public.claim_item(bigint) to authenticated;
grant execute on function public.unclaim_item(bigint) to authenticated;
alter table public.items replica identity full;
do $$ begin
  alter publication supabase_realtime add table public.items;
exception when duplicate_object then null;
end $$;
do $$ begin
  alter publication supabase_realtime add table public.activity_logs;
exception when duplicate_object then null;
end $$;

-- 執行完上面的 SQL 後，把你的帳號設成管理員：
-- update public.profiles set is_admin = true where email = '你的 Email';
